PRIMARY_KEY_FIELD_NAME = "OBJECTID"

# input parameters constants
PARAMETER_DEM = 0
PARAMETER_SOIL = 1
PARAMETER_SOIL_TYPE = 2
PARAMETER_VEGETATION = 3
PARAMETER_VEGETATION_TYPE = 4
PARAMETER_PATH_TO_RAINFALL_FILE = 5

# PARAMETER_DELTA_T = 6
PARAMETER_MAX_DELTA_T = 6

PARAMETER_END_TIME = 7
PARAMETER_SURFACE_RETENTION = 6  # nula jen docasne, typ vypoctu se resi jinak
PARAMETER_POINTS = 8
PARAMETER_PATH_TO_OUTPUT_DIRECTORY = 9

#
PARAMETER_SOILVEGTABLE = 10
PARAMETER_SOILVEGTABLE_CODE = 11
PARAMETER_STREAM = 12
PARAMETER_STREAMTABLE = 13
PARAMETER_STREAMTABLE_CODE = 14
PARAMETER_ARCGIS = 15
PARAMETER_DPRE_ONLY = 16

PARAMETER_MFDA = 17
PARAMETER_EXTRA_OUTPUT = 18
PARAMETER_INDATA = 19
PARAMETER_PARTIAL_COMPUTING = 20
PARAMETER_DEBUG_PRT = 21
PARAMETER_PRINT_TIME = 22
PARAMETER_TYPE_COMPUTING = 23     # nula jen docasne, typ vypoctu se resi jinak
