# input parameters constants
PARAMETER_DEM = 0
PARAMETER_SOIL = 1
PARAMETER_SOIL_TYPE = 2
PARAMETER_VEGETATION = 3
PARAMETER_VEGETATION_TYPE = 4
PARAMETER_PATH_TO_RAINFALL_FILE = 5

PARAMETER_MAX_DELTA_T = 6

PARAMETER_END_TIME = 7
PARAMETER_SURFACE_RETENTION = 6  # nula jen docasne, typ vypoctu se resi jinak
PARAMETER_POINTS = 8
PARAMETER_PATH_TO_OUTPUT_DIRECTORY = 9

PARAMETER_SOILVEGTABLE = 10
PARAMETER_SOILVEGTABLE_CODE = 11
PARAMETER_STREAM = 12
PARAMETER_STREAMTABLE = 13
PARAMETER_STREAMTABLE_CODE = 14
PARAMETER_DPRE_ONLY = 15
