#!/usr/bin/python
# -*- coding: latin-1 -*-
# SMODERP 2D
# Created by Jan Zajicek, FCE, CTU Prague, 2012-2013

import math

# input parameters constants
PARAMETER_DMT = 0
PARAMETER_SOIL = 1
PARAMETER_SOIL_TYPE = 2
PARAMETER_VEGETATION = 3
PARAMETER_VEGETATION_TYPE = 4
PARAMETER_PATH_TO_RAINFALL_FILE = 5

#PARAMETER_DELTA_T = 6
PARAMETER_MAX_DELTA_T = 6

PARAMETER_END_TIME = 7
PARAMETER_SURFACE_RETENTION = 8
PARAMETER_POINTS = 9
PARAMETER_PATH_TO_OUTPUT_DIRECTORY = 10
PARAMETER_TYPE_COMPUTING = 11
PARAMETER_MFDA = 12
PARAMETER_SOILVEGTABLE = 13
PARAMETER_SOILVEGTABLE_CODE = 14
PARAMETER_STREAM = 15
PARAMETER_STREAMTABLE = 16
PARAMETER_STREAMTABLE_CODE = 17
PARAMETER_ARCGIS = 18
PARAMETER_EXTRA_OUTPUT = 19
PARAMETER_INDATA = 20
PARAMETER_PARTIAL_COMPUTING = 21
PARAMETER_DEBUG_PRT = 22
PARAMETER_PRINT_TIME = 23


# calculation constants
FB = math.pi / 4 # facet boundary
PI_HALF = math.pi / 2
THREE_PI_HALF = 3 * math.pi / 2
VE = 4 #variable exponent
RILL_RATIO = 0.7
