# TENTO SOUBOR SE GENERUJE AUTOMATICKY V bash/testy-delej-vse.sh
python start-smoderp2d.py --indata bash/test-in/trych01-krabice-mala.in roff > bash/test-out/trych01-krabice-mala.log
python start-smoderp2d.py --indata bash/test-in/trych01-krabice-velka.in roff > bash/test-out/trych01-krabice-velka.log
python start-smoderp2d.py --indata bash/test-in/trych01-pulz.in roff > bash/test-out/trych01-pulz.log
python start-smoderp2d.py --indata bash/test-in/trych01-trojuhelnik.in roff > bash/test-out/trych01-trojuhelnik.log
python start-smoderp2d.py --indata bash/test-in/trych01-velbloud.in roff > bash/test-out/trych01-velbloud.log
python start-smoderp2d.py --indata bash/test-in/trych02-krabice-mala.in roff > bash/test-out/trych02-krabice-mala.log
python start-smoderp2d.py --indata bash/test-in/trych02-krabice-velka.in roff > bash/test-out/trych02-krabice-velka.log
python start-smoderp2d.py --indata bash/test-in/trych02-pulz.in roff > bash/test-out/trych02-pulz.log
python start-smoderp2d.py --indata bash/test-in/trych02-trojuhelnik.in roff > bash/test-out/trych02-trojuhelnik.log
python start-smoderp2d.py --indata bash/test-in/trych02-velbloud.in roff > bash/test-out/trych02-velbloud.log
python start-smoderp2d.py --indata bash/test-in/trych05-krabice-mala.in roff > bash/test-out/trych05-krabice-mala.log
python start-smoderp2d.py --indata bash/test-in/trych05-krabice-velka.in roff > bash/test-out/trych05-krabice-velka.log
python start-smoderp2d.py --indata bash/test-in/trych05-pulz.in roff > bash/test-out/trych05-pulz.log
python start-smoderp2d.py --indata bash/test-in/trych05-trojuhelnik.in roff > bash/test-out/trych05-trojuhelnik.log
python start-smoderp2d.py --indata bash/test-in/trych05-velbloud.in roff > bash/test-out/trych05-velbloud.log
python start-smoderp2d.py --indata bash/test-in/trych01dist-krabice-mala.in roff > bash/test-out/trych01dist-krabice-mala.log
python start-smoderp2d.py --indata bash/test-in/trych01dist-krabice-velka.in roff > bash/test-out/trych01dist-krabice-velka.log
python start-smoderp2d.py --indata bash/test-in/trych01dist-pulz.in roff > bash/test-out/trych01dist-pulz.log
python start-smoderp2d.py --indata bash/test-in/trych01dist-trojuhelnik.in roff > bash/test-out/trych01dist-trojuhelnik.log
python start-smoderp2d.py --indata bash/test-in/trych01dist-velbloud.in roff > bash/test-out/trych01dist-velbloud.log
python start-smoderp2d.py --indata bash/test-in/konk01-krabice-mala.in roff > bash/test-out/konk01-krabice-mala.log
python start-smoderp2d.py --indata bash/test-in/konk01-krabice-velka.in roff > bash/test-out/konk01-krabice-velka.log
python start-smoderp2d.py --indata bash/test-in/konk01-pulz.in roff > bash/test-out/konk01-pulz.log
python start-smoderp2d.py --indata bash/test-in/konk01-trojuhelnik.in roff > bash/test-out/konk01-trojuhelnik.log
python start-smoderp2d.py --indata bash/test-in/konk01-velbloud.in roff > bash/test-out/konk01-velbloud.log
python start-smoderp2d.py --indata bash/test-in/konv01-krabice-mala.in roff > bash/test-out/konv01-krabice-mala.log
python start-smoderp2d.py --indata bash/test-in/konv01-krabice-velka.in roff > bash/test-out/konv01-krabice-velka.log
python start-smoderp2d.py --indata bash/test-in/konv01-pulz.in roff > bash/test-out/konv01-pulz.log
python start-smoderp2d.py --indata bash/test-in/konv01-trojuhelnik.in roff > bash/test-out/konv01-trojuhelnik.log
python start-smoderp2d.py --indata bash/test-in/konv01-velbloud.in roff > bash/test-out/konv01-velbloud.log
